### ISSUE TITLE
A number of errors on Rpi 4

### ISSUE THREAD

**Issue by scottsweb** [woahbase/alpine-pulseaudio#4]
I am seeing a couple of errors on startup and wondering if you can help me debug them:

First:
```
E: [pulseaudio] ltdl-bind-now.c: Failed to open module /usr/lib/pulse-12.2/modules/module-udev-detect.so: Error relocating /lib/libudev.so.1: name_to_handle_at: symbol not found
E: [pulseaudio] module.c: Failed to open module "module-udev-detect".
```

Second:
On first start I see logs notifying me about a missing pulse audio cookie, this seems to go after the first start.

Third:
I am endind up with a `auto_null` audio device: 

```
D: [pulseaudio] module-always-sink.c: Autoloading null-sink as no other sinks detected.
I: [pulseaudio] sink.c: Created sink 0 "auto_null" with sample spec s16le 2ch 44100Hz and channel map front-left,front-right
```

My compose file is:

```
version: '2'
services:
    mycroft:
        image: woahbase/alpine-pulseaudio:armhf
        volumes:
            - "/etc/asound.conf:/etc/asound.conf:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - "/var/run/dbus:/var/run/dbus"
        devices:
            - "/dev/snd:/dev/snd:rwm"
        ports:
            - "4713:4713"
        environment:
            - PGID=1001
            - PUID=1001
            - DISABLEBLUETOOTH=true
        restart: always
        privileged: true
        network_mode: host
        cap_add:
            - NET_ADMIN
        container_name: pulseaudio
        hostname: pulseaudio
```
